#pragma once
#include "gui_manager.hpp"
#include "math.hpp"
#include "window.hpp"
#include "renderer.hpp"
#include "deleter.hpp"
#include "logger.hpp"
#include "extended_functions.hpp"
#include "component/component.hpp"
